name: Manga

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
  workflow_dispatch:
 
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.manga.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: GoncaloP0710
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading, planning, completed
          plugin_anilist_limit: 2
