name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_anilist: yes
          plugin_anilist_user: GoncaloP0710
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 5
