name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push:
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_anilist: yes
          plugin_anilist_user: GoncaloP0710
      - name: Commit metrics
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add github-metrics.svg
          git commit -m "Update metrics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}